print("What is your name?")
name = input()
print("Hello " + name + "! I hope you're doing well :)")
print("Let's crunch some numbers! Give me two and I'll add them for ya.")
number1 = input("Number 1: ")
number2 = input("Number 2: ")
sum = int(number1) + int(number2)
print("Here's your answer!")
print(number1 + " + " + number2 + " =", sum)